# Generated by Django 5.2.15 on 2026-07-02 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('tests', '0002_assessmentattempt_attemptquestion_candidateanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='tests.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
